### PR TITLE
Use consistent indent in hook.sh

### PR DESCRIPTION
**Pull request by glensc**
Some of the functions were indented with 2 spaces, some others with 4 spaces. this makes it consistent with 2 spaces.

Use this link to see non-whitespace changes:
- https://github.com/dehydrated-io/dehydrated/pull/841/files?w=1

See GitHub documentation:
- https://github.blog/2018-05-01-ignore-white-space-in-code-review/

### CODE REVIEW

**Comment by lukas2511** [comment]
thx, merged

**Comment by glensc** [comment]
seems cherry-picked or something as https://github.com/dehydrated-io/dehydrated/commit/e17456778f25326dc14bd8324ae70dd352d3578a

**Comment by lukas2511** [comment]
> seems cherry-picked or something as [e174567](https://github.com/dehydrated-io/dehydrated/commit/e17456778f25326dc14bd8324ae70dd352d3578a)

yea, i'm mostly doing that so i can ff-only merge pull-requests and keep as many commits signed as possible

**Comment by glensc** [comment]
@lukas2511 You can do that from GitHub UI as well, enable ff-merges in settings and then it appears in button-dropdown.

the downside is that it will also squash

image

**Comment by lukas2511** [comment]
> @lukas2511 You can do that from GitHub UI as well, enable ff-merges in settings and then it appears in button-dropdown.
> 
> the downside is that it will also squash
> 
> image

yea but it's not signed if i do it that way. also i like a good preview of my merge and do some testing before pushing it (not really relevant with these changes, but sometimes with others).

**Pull request closed without merging**
