### PR TITLE
FIX dns-01 domain + wildcard walidation (#674)

### PR DESCRIPTION
**Pull request by fandauchytil**
Fix for issue #674.

### CODE REVIEW

**Comment by txr13** [comment]
How does this purport to fix the issue? The only changes are to move a non-chained hook’s deploy sequence to within the validation sequence. This will affect all hooks, not just those used for DNS.

The issue linked appears to be a case of one validation record being overwritten by another. That is a known issue with some DNS providers or hook scripts, but it is not a flaw in dehydrated. I would be very wary of trying to remedy it by introducing a change for all hook scripts regardless of whether they suffer this issue or not.

**Comment by fandauchytil** [comment]
Yes, you are right. I didn't understand issue with "potential huge TTL" and its consequences. In my commit[1], I wanted to show what I need [1], and if I add an additional condition, it cloud be an option. But it looks like I'm anomaly (#554), so I have no problem with local patch. Thank you for your time.

[1] I did not found a better way on github how to show a prototype.
[2] I need (want) to do some sequential stuff.

**Comment by fandauchytil** [comment]
I added variable 'HOOK_SEQ', it will trigger sequential "deploy challenge" for every "challenge verification".

I tested original functionality and it should work without breakage (code path is the same). Please look at it and tell me if it's ok, or if some more changes will be needed (or if you will not accept it by principle -- I'll have no problem with it, it's your project, but please let me know).

**Comment by txr13** [comment]
So, having read through the code, I want to double-check my understanding of the proposed changes:

1. `HOOK_CHAIN` and `HOOK_SEQ` are mutually incompatible options, with `HOOK_CHAIN` overriding `HOOK_SEQ`.

2. No message will be logged regarding the cleaning of challenge tokens if `HOOK_CHAIN="no"` and `HOOK_SEQ="yes"`.

3. `HOOK_SEQ` is supported for use in a per-certificate config file.

Is my understanding correct? You may wish to add additional commits updating the appropriate documentation for per-certificate configs and the main config. You may also want to make it clear to the user that using `HOOK_CHAIN="yes"` will have the same effect as setting `HOOK_SEQ="no"` because they are mutually incompatible.

All in all, I still feel this is a very niche case to work around broken implementations which don't correctly support multiple TXT records per hostname. It would probably be better if people just moved to a working implementation instead. Still, that's not my decision to make. :)

**Comment by fandauchytil** [comment]
Yes, you are correct in everything... I thought very hard about this and I'm not happy with this hack (I use it only on one legacy system I'm stuck with and after upgrade, there will be no real need for this). Dehydrated is excellent project and I don't want to taint it by this. Nonetheless, if you think, that I should finish it, I will.

Thank you very much for your time, I really appreciate it :).

**Comment by lukas2511** [comment]
Closing this as it's not really relevant for most users and unless behaviour gets configurable this might cause problems for others.

**Pull request closed without merging**
